### ISSUE TITLE
Assemble stage

### ISSUE THREAD

**Issue by charlestietjen** [charlestietjen/untitled-mechjam#6]
- Add additional ships to background
- Define waves to spawn
- Add patrol markers for waves to follow
- Contain waves in a parent group, listen for them leaving the node tree
- Advance stage based on number of remaining enemies
- Enemies select a patrol node after a timeout
- - assign a random wait time in a range
- - Enemies should stop moving briefly when choosing a new destination
- A ranged enemy would be a significant addition

**Comment by Phizzard** [comment]
### Added some extra ships in the background with some looking further in the background

### Created an EnemySpawner Scene
- `wave_size` is how many groups of enemies a spawner can have
- `group_size` can determine how many enemies spawn in a group
- `spawn_interval` is the interval between spawns. Once the wave_size * group_size has been reached the timer will stop
- Enemy spawner's Spawn path gives some randomness to an enemy group's spawn point to avoid colliding, could do with some tweaking, I assume scaling the instance of it in skymap could even work

### Updated Valgr's raycasts to add more cone shaped points
- AFAIA this isn't the best way to do it, but with the few enemies on screen it should be fiiiiiiine
- Mostly did this because in the case of enemies colliding and getting pushed around to face different ways they can still likely detect the enemy and not be lost in the Z axis

**Comment by charlestietjen** [comment]
To do if either if us get the time:

- Remove existing statically placed enemies
- Add 2 or more spawners, they can go in the foreground or background just fine but keep x and y within the playable area border
- A top level script to manage the spawners
- Keep the waves infinite

**Comment by charlestietjen** [comment]
I added a really basic signal check for enemy deaths and incremented group size and wave size when a spawner has no enemies left, works surprisingly well
